### ISSUE TITLE
doesnt run

### ISSUE THREAD

**Issue by jamesmckeever** [CasperDoesCoding/account-manager#4]
program will just not run in any capacity, opens cmd and closes instantly

**Comment by CasperDoesCoding** [comment]
Are you aware on how to locate the directory where the files are using cmd?

**Comment by jamesmckeever** [comment]
In what capacity? I try to run start.bat and i just get a momentary cmd window with "directory + python main.py". I have python installed

**Comment by CasperDoesCoding** [comment]
If you could open the main directory with cmd and try running the program there then it should give you an error instead of instantly closing.
![step1](https://user-images.githubusercontent.com/105428570/175286849-f16d384f-0257-463e-b350-e70777925955.png)
![step2](https://user-images.githubusercontent.com/105428570/175286852-31942131-aaf8-438c-8633-81ba6b42485c.png)
![step3](https://user-images.githubusercontent.com/105428570/175286855-8e2dda63-bc81-4b45-96a2-983e43478b8e.png)

**Comment by CasperDoesCoding** [comment]
As shown after you have opened the cmd prompt type in "python main.py"
